<a href="https://colab.research.google.com/github/manojsankarkumar/manojsankarkumar.github.io/blob/master/Advanced_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Top 8 powerful functions in Python for Deeper Data Analysis

1. Groupby
2. pivot_table
3. Aggregate
4. cross_tab
5. concat
6. apply
7. lambda
8. del (keyword)

## 1. Groupby

In [2]:
import pandas as pd

insurance_data = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

#### 1.1 Perform Initial Analysis

In [3]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
insurance_data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [7]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [8]:
insurance_data["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

#### 1.2 Pull up the average insurance charges based on region

In [13]:
insurance_data.groupby(by="region")["charges"].mean().round(2).sort_values(ascending=False) #Chain method

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

#### 1.3 Pull up the average insurance charges based on region and sex

### Discrete and Continuous data

* Discrete - Just countable / can't be Segmented
* Continuous - Measurable/Have units/Can also be segmented

In [18]:
insurance_data.groupby(by=["region","sex"])["charges"].mean().round(2).sort_values(ascending=False) #Chain method

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

## 2. Pivot table

In [7]:
import pandas as pd

# Load the data first
insurance_df = pd.read_csv("/content/drive/MyDrive/Python - Data Analysis/Insurance.csv")

pd.pivot_table(data=insurance_df,values=["charges"],index="region",columns=["sex","children"]).round(2) # presentable comparing 2 categorical features vs 1 continuous data

            charges                                                    \
sex          female
children          0         1         2         3         4         5
region
northeast   9789.82  17124.69  14523.22  13730.10  14542.42       NaN
northwest  12583.87  11118.86  13127.59  13430.71  11024.42   8965.80
southeast  14862.01   9869.91  11766.31  19722.98  18267.10   9923.89
southwest  10149.75  10841.64  16230.26   8438.74  10945.68  10023.65


sex            male
children          0         1         2         3         4         5
region
northeast  13389.64  15474.29  12317.91  14935.22  14442.28   6978.97
northwest   9812.97   9515.04  13762.55  22971.22  11508.32       NaN
southeast  13791.81  17424.65  18647.95  17101.82   8726.91  10306.99
southwest  13727.26   9971.33  18875.95  12071.59  17923.95   6864.67

## 3. Aggregate

In [4]:
import pandas as pd

# Load the data first
insurance_df = pd.read_csv("/content/drive/MyDrive/Python - Data Analysis/Insurance.csv")
insurance_df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

##### 3.1 Find out the average insurance charges based on Region

In [5]:
insurance_df.groupby(by=["region","sex"])["charges"].mean().round(2).sort_values(ascending=False) #Chain method

region     sex
southeast  male      15879.62
northeast  male      13854.01
southeast  female    13499.67
southwest  male      13412.88
northeast  female    12953.20
northwest  female    12479.87
           male      12354.12
southwest  female    11274.41
Name: charges, dtype: float64

In [13]:
insurance_df.groupby(by=["region","sex"])["charges"].agg(func=["mean","min","max","sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

## 4. CrossTab

In [14]:
import pandas as pd

# Load the data first
insurance_df = pd.read_csv("/content/drive/MyDrive/Python - Data Analysis/Insurance.csv")
insurance_df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

##### 4.1 Find out the Smokers and Non-Smokers region-wise.

In [21]:
pd.crosstab(index=insurance_df["region"],columns=insurance_df["smoker"],margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

## 5. Concat

In [26]:
sales_data_2017 = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales Transactions-2017.csv")
sales_data_2018 = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales Transactions-2018.csv")
sales_data_2019 = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales Transactions-2019.csv")

sales_full_data = pd.concat(objs=[sales_data_2017,sales_data_2018,sales_data_2019])
sales_full_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [27]:
sales_full_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [28]:
sales_full_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

## 6. Apply

In [29]:
import pandas as pd

# Load the data first
insurance_df = pd.read_csv("/content/drive/MyDrive/Python - Data Analysis/Insurance.csv")
insurance_df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [31]:
insurance_df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

#### 6.1 Create a new column in the same dataframe with the name 'Eligibility Criteria' where if age is > 20, say Eligible else not

In [36]:
def get_age(x):
  if x > 20:
    return "Eligible"
  else:
    return "Not eligible"

In [37]:
insurance_df["Eligibility Criteria"] = insurance_df['age'].apply(get_age)
insurance_df

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

## 7. Lambda

* Anonymous function italicized text/ nameless function

In [38]:
insurance_df

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

In [39]:
insurance_df["Eligibility Criteria_1"] = insurance_df['age'].apply(lambda x:1 if x > 20 else 0)
insurance_df

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,Eligibility Criteria_1
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible,0
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible,0
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,1
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,1
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,1
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,1
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible,0
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible,0
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,1
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,1

## 8. Del

In [40]:
del insurance_df["Eligibility Criteria_1"]
insurance_df

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible