<a href="https://colab.research.google.com/github/manojsankarkumar/manojsankarkumar.github.io/blob/master/Chapter_4_(Tasks)_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Task 1: Data cleaning challenge on sales data

In [2]:
import pandas as pd

In [ ]:
# Data cleaned - this is the final which needs to be achieved
sales_edited = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales-Transactions-Edited.csv")
sales_edited

In [2]:
# Step 1: Load and combine the data to one - sales_all
import pandas as pd

sales_2017 = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales Transactions-2017.csv")
sales_2018 = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales Transactions-2018.csv")
sales_2019 = pd.read_csv(filepath_or_buffer="/content/drive/MyDrive/Python - Data Analysis/Sales Transactions-2019.csv")

sales_all = pd.concat(objs=[sales_2017,sales_2018,sales_2019])
sales_all

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [55]:
# Step 2: Shape of uncleaned data
sales_all.shape

(111206, 9)

In [56]:
# Step 3: Remove blank rows

sales_cleaned_df = sales_all.dropna(subset=['Date', 'Voucher', 'Party', 'Product'], how='all')

sales_cleaned_df.shape

(111200, 9)

In [57]:
# Step 4: Remove total rows
sales_cleaned_df = sales_cleaned_df[~sales_cleaned_df['Voucher'].astype(str).str.contains('Total', na=False)]
sales_cleaned_df = sales_cleaned_df[~sales_cleaned_df['Party'].astype(str).str.contains('Total', na=False)]

sales_cleaned_df.shape

(111166, 9)

In [59]:
# Step 5: Clean number columns

numeric_column = ['Qty', 'Rate', 'Gross', 'Disc', 'Voucher Amount']

sales_cleaned_df[numeric_column] = sales_cleaned_df[numeric_column].apply(lambda x: pd.to_numeric(x.astype(str).str.replace(',',''),errors='coerce'))

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,NaN,13100.0
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,NaN,30990.0
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,NaN,NaN
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,NaN,NaN
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,NaN,NaN
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,NaN,NaN
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,NaN,NaN

In [60]:
# Step 6: Convert date to date type

sales_cleaned_df['Date'] = pd.to_datetime(sales_cleaned_df['Date'],dayfirst=True,errors='coerce')

sales_cleaned_df = sales_cleaned_df.dropna(subset=['Date'])

#sales_cleaned_df.dtypes

sales_cleaned_df #After dropping the dates, we get the required number of rows as shown in cleaned dataset

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,NaN,13100.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,NaN,NaN
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,NaN,30990.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,NaN,NaN
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0,NaN,NaN
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0,NaN,NaN
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0,NaN,NaN
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0,NaN,NaN
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0,NaN,NaN

In [49]:
# Step 7: Drop the unwanted columns

sales_cleaned_df = sales_cleaned_df.drop(columns=['Gross','Disc','Voucher Amount'])

sales_cleaned_df

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0
...,...,...,...,...,...,...
19167,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0
19168,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4
19169,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0
19170,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5
19171,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0

In [51]:
# Step 8: Drop the index column

sales_cleaned_df.drop(sales_cleaned_df.columns[0],axis=1)

sales_cleaned_df

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0
...,...,...,...,...,...,...
95557,2019-10-10,Sal:4935,K.SRIHARI,16*20(100-W),140.0,26.0
95558,2019-10-10,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4
95559,2019-10-10,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0
95560,2019-10-10,Sal:4935,K.SRIHARI,10*12 RK,800.0,8.5
95561,2019-10-10,Sal:4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0

#### Task 2: Merge function 1 example

In [ ]:
import pandas as pd
sales_merged = pd.merge(sales_2017,sales_2018,on='Party')
sales_merged

#### Task 3: List comprehension 2 example

In [5]:
numbers = [1,2,3,4,5,6,7,8,9,10]
square_of_numbers = [x ** 2 for x in numbers]
print(square_of_numbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [7]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
gen_list = [x for x in fruits if "n" in x]

print(gen_list)

['banana', 'mango']

#### Task 4: Lambda function 2 example with Map, Filter, Reduce

###### Map

In [8]:
numbers = [1, 2, 3, 4, 5]

result = list(map(lambda x: x * 2, numbers))

print(result)

[2, 4, 6, 8, 10]

In [9]:
names = ['Arun', 'Babu', 'Chandru']

result = list(map(lambda x: x.upper(), names))

print(result)

['ARUN', 'BABU', 'CHANDRU']

###### Filter

In [13]:
numbers = [1, 2, 3, 4, 5, 6]

result = list(filter(lambda x: x % 2 == 0, numbers))

print(result)

[2, 4, 6]

In [14]:
names = ['Arun', 'Babu', 'Chandru']

result = list(filter(lambda x: len(x) > 4, names))

print(result)

['Chandru']

###### Reduce

In [16]:
from functools import reduce

numbers = [1, 2, 3, 4, 5]

result = reduce(lambda x, y: x + y, numbers)

print(result)

15

In [17]:
from functools import reduce

numbers = [3, 7, 1, 9, 4]

result = reduce(lambda x, y: x if x > y else y, numbers)

print(result)

9